### ISSUE TITLE
Do we really need to hide the contextual-navigation..?

### ISSUE THREAD

**Issue by planctus** [ec-europa/ecl-twig#153]
While reviewing the auto-init implementation on the twig side i noticed that this was applied also to a component not visible in storybook.

This component is the contextual-navigation, and basing on https://webgate.ec.europa.eu/CITnet/jira/browse/INNO-1508 we assumed the component was to be hidden also in ecl-twig.
I believe the situation we created is not acceptable, we might remove the component if it's outdated or whatever reason designers might have for removing it, but if we keep working on it, updating it and releasing it as a package and the designers are still expecting this component to be implemented in the mocks they produce there's no reason why hiding it, IMHO.

**Comment by planctus** [comment]
@papegaill, @yhuard , @emeryro , @kalinchernev

**Comment by yhuard** [comment]
As far as I remember, the design team asked us to hide it for many reasons (not clear what it is, how it works, when to use it, etc.). At this point, it means the component is not officially supported anymore. On our side, we couldn't just delete it (backward compatibility), that's why we kept it. We shouldn't work on it anymore until further notice... but maybe I have worked on it to add the auto-init functionality, I don't remember to be honest. If that's the case, it's not a big change anyway (just adding an HTML attribute on the parent tag), is it?
Since the component is hidden, it should not appear in the mocks...

**Comment by planctus** [comment]
interestingly enough i've just discovered that we are not only hiding the component in storybook but since 2.9.0 we actually removed it from npm...
https://github.com/ec-europa/ecl-twig/pull/119/files#diff-6971956b2610a025ea0014ce1a2fb601
I don't think this was on purpose, can you confirm @yhuard that for how weird it is we are only supposed to hide the demo but still releasing the package?
(I noticed this while writing a script to automate the checks on the packages to be released... :) )
@papegaill @serotonine

**Comment by papegaill** [comment]
@planctus indeed, seems strange to have replaced the contextual-navigation by menu-legacy component? @serotonine ?

**Comment by serotonine** [comment]
Hello I think I rename this after @emeryro comment...
