### ISSUE TITLE
[RFC] Versioning of ECL-twig

### ISSUE THREAD

**Issue by emeryro** [ec-europa/ecl-twig#81]
This is a RFC on version management for ECL-twig

# Current situation (2019-03-21)

- All ecl-twig components have version 0.0.1-alpha
- Dependencies to ECL packages are mostly using `^2.1.1` (sometimes `^2.1.0` or `~2.1.0`)

# Main questions

- How should we version ECL-twig packages?
- How should we manage dependencies?

## Version of ECL-twig packages

As components are rather stable now, we should consider updating their version (at least removing the alpha status).
There are several options (not exaustive)

### Dedicated flow

Put ECL-twig components to version 1.0 (if we consider that they are mature enough), then increment the version independently to ECL.

*Pros*

- Quite straightforward; we just increment the version (major or minor) depending on the changes

*Cons*

- Disconnected to ECL, so it may be harder for users to know which version correspond to what

### Tied flow

Put ECL-twig components to the same version as ECL they rely on and keep them at the same version as ECL later on.

*Pros*

- Easy to understand for the users

*Cons*

- Maybe not flexible enough; ECL-twig may require more or less update than ECL

### Mixed flow

Put ECL-twig components to the same major version as ECL, but keep a dedicated flow for minor and patches.

This keeps mostly the same pros and cons as previous options, but attenuated.

## Dependencies version

see https://docs.npmjs.com/files/package.json#dependencies. 
Some possibilities (not exaustive) from the safest (but maintenance expensive) to the "riskiest" (but cheapest):

- Using strict version: `2.1.1`
- Using tilde range: `~2.1.1`, i.e. `>=2.1.1 <2.2.0`
- Using carret range: `^2.1.1`, i.e. `>=2.1.1 <3.0.0`

**Comment by yhuard** [comment]
What others do:
- Carbon: https://github.com/IBM/carbon-components, https://github.com/IBM/carbon-components-react, https://github.com/IBM/carbon-components-angular all have different major version
- Material: https://github.com/material-components/material-components-web, https://github.com/material-components/material-components-web-react, https://github.com/material-components/material-components-web-components have different major versions, but the main repo is only in v1.x.x (others are v0.x.x)

Seems like it's not too disturbing to have different major versions 😉 

We could have different majors of ECL Twig for a same ECL version, but upgrading to a new major version of ECL should be translated into a new major version of ECL Twig.

I'd go for the Dedicated flow 👍 

For the other points (strict vs tilde vs carret), we need more research. What's the impact of updating the ECL version of a component? Should all the dependencies to the vanilla components be aligned?

**Comment by emeryro** [comment]
To move forward on this discussion, here is my proposal:

- We set version 1.0 to all twig components as they are today (considered stable)
- We use carret range for both `dependencies` and `devDependencies` (i.e. `^2.3.0` for ECL and `^1.0` for ECL-twig)

Then depending on the scenario:

**ECL has been updated to a minor or fix version**
- as we use carret range, ECL-twig components will still use the latest version of ECL packages. And as we ensure that there is no breaking change, they should still work correctly.
- when we apply these changes, we update all ECL-twig components version to a the next minor or fix one; this update may represent several updates of ECL (ECL-twig `1.1` may include ECL `2.4.0`, `2.5.0` and `2.5.1` for instance)
- we update devDependencies to ECL to the latest available (still using carret range)
- we update dependencies to ECL-twig components to the latest one (still using carret range)

**ECL has been updated to a major version**
- as we use carret range, ECL-twig component will continue to use the previous major version as devDependencies (so no sudden break)
- when we apply these changes, we update all ECL-twig components to the next major one; again, it may represent several ECL updates
- we update devDependencies to ECL to the latest available (still using carret range)
- we update dependencies to ECL-twig components to the latest one (still using carret range)

**ECL-twig component needs to be updated**
- we update the component (or components), and update version of ECL-twig components to next minor/fix one
- we update dependencies to ECL-twig components to the latest one (still using carret range)

Note:
of course, some of these operation may be automated (changing dependencies version for instance)

**Comment by yhuard** [comment]
> - We set version 1.0 to all twig components as they are today (considered stable)

ok but first in beta, the time we test the publishing process works fine

> We use caret range for both dependencies and devDependencies (i.e. ^2.3.0 for ECL and ^1.0 for ECL-twig)

ok

here's what I'd do for the rest:

**ECL has been updated to a fix version**

if there's no impact on the markup, do nothing

**ECL has been updated to a minor version**

minor means new features (new component, new attributes in the markup) 
-> we need to update the twig templates or to create a new one
-> only update/create the components impacted by the update
-> these new or updated components must depend on the latest version of ECL
-> untouched components will still rely on the previous ECL version
this way, only new or updated twig components will be published, the other are still valid

**ECL has been updated to a major version**

won't happen any time soon :D but I guess we'd make a new major version of ECL Twig as well

**ECL-twig component needs to be updated**

e.g. we need to fix the markup because of an error introduced on this side (not on ECL side)

-> we try to fix it without introducing breaking changes
-> if we have no choice but to introduce a breaking change, create a new major version of ECL Twig

**Comment by yhuard** [comment]
TODO: define what a breaking change is in terms of Twig components

in a nutshell, it's when we change the API of the template

in most cases, we should be able to avoid breaking changes by providing defaults for new parameters, by mapping renamed parameters

**Comment by kalinchernev** [comment]
I'd say the dedicated flow gives the most flexibility in terms of maintaining two projects in parallel.
Easiness of having matching versions is not as important of an argument as having the flexibility to iterate independently.
So I also vote for dedicated flow option.

Regarding dependencies, I'd personally prefer the tilde range as it should be safer.

**Comment by degliwe** [comment]
ECL and ECL-twig are different products so it make sense for them to have a different versioning.
However we want to avoid ambiguity, we already ship twig packages in v1 like ecl-accordion.
It makes it a bit confusing is a release another ecl-accordion in v1.

In order to make it very clear, I would suggest to rename the repo ECL-twig -> ECL2-twig so that we remove all ambiguity. Our twigs starting from v1 are for ECL2.

Later on for an hypothetical ECL3 we will release ECL3-twig.

**Comment by yhuard** [comment]
Then `@ecl-twig/ec-components` becomes `@ecl2-twig/ec-components`, fine for me. 👍 Should we rename the repo as well?

**Comment by kalinchernev** [comment]
To be honest, I think the existing namespaces (npm organizations) already provide enough distinction. I'd rather put a table with notes on namespaces in the main README of repositories rather than placing a version in the namespace.

**Comment by yhuard** [comment]
> Regarding dependencies, I'd personally prefer the tilde range as it should be safer.

Can you give a concrete example please? :) Would you use the tilde everywhere or just in the internal dependencies (ie. between twig packages)?

**Comment by kalinchernev** [comment]
For internal dependencies within a monorepo, we've been using the carret, we haven't had issues so far :)
Though when an ecl-twig component depends on a resource out of the monorepo, then tilde.

**Comment by planctus** [comment]
My first reaction was in favour of a "mixed flow", it is true that ecl-twig is a product per se but it has a dependency on ECL so keeping the twig components in an unrelated state compared to the vanilla ones seems to me "artificial" and not usefully "descriptive" of what the version of the component comes with.

At the same time it is true that we might have to make independent releases, especially in twig, but it looks like something we could handle this with minor releases on top of the "latest" release of the vanilla components but i see how this would hardly be considered "semantic versioning".
Furthermore, here there's a grey area , would we then apply this new minor to the vanilla components? i'd say no, i would imagine ECL  being 2.1, for instance and twig being 2.1.6 (if we make six iteration on this version in twig) so i'm simply thinking about versioning twig adaptations as patches to the ECL...questionable, i see :)

Anyway, in this case tilde would be used for all the ECL dependencies since all the ECL releases would require a release also in twig in order to be reflected there.

In any case the idea of moving the all repository's namespace seems to me unneeded, we have twig in ECL v1, true, and this could cause some confusion for the time being, but if we are able to make V2 usable nobody is going to use V1 anymore and this is what i would push for instead of creating a potentially "stable" dualism between the two.

I tried to write down this, even though i have myself many doubts and i appreciate all the opinions here, probably more than mine :)

**Comment by yhuard** [comment]
Hi @ec-europa/inno 

We have to move forward on this topic!

**Comment by ademarco** [comment]
Hello! Yep, we would need a release as soon as possible as we have started porting the OpenEuropa theme to ECL 2.0. Thanks!

**Comment by emeryro** [comment]
so... We seems to have several proposals here.
If I try to summarize:
1- use another repo for ECL2 twig (for instance `@ecl2-twig/ec-components`) and start versioning with 1.0 (or 1.0-beta)
2- keep the same repo for ECL2 twig and follow version number of ECL2. So first release would be 2.5.0. We could use fix versions for twig only releases.
3- keep the same repo for ECL2 twig and provide some sort of mapping table to indicate which version of ECL twig correspond to which vanilla ECL version.

**Comment by emeryro** [comment]
option 1 is probably the most straightforward, in my mind

**Comment by planctus** [comment]
I do opt for tying the twig implementation of the components to the vanilla version of them, despite the fact that it would also be possible to version them independently i see this as a potential cause of confusion by the "adopters" and i tend to see the implementation as something that doesn't exist without the "definition". 
I do also see that this doesn't imply a common versioning, so i'm not against going for a dedicated flow if that's the option we would go for, absolutely, that way things look more "straightforward", it's a dedicated flow..

**Comment by yhuard** [comment]
1. At the level of this repository, do we all agree that every package (i.e. every component) use the same version number? In other words, we won't find `@ecl-twig/ec-button 2.4.2` alongside  `@ecl-twig/ec-link 2.8.3`.

2. Basically, we have 2 options (we can discard option 3). Either we decouple the versioning of the twig templates from the versioning of the CSS framework, or we couple them. @emeryro is in favor of decoupling, @planctus is in favour of tying them. I'd add that if we tie the versioning, we would only have the same MAJOR.minor versions, patches could be different. For example: `@ecl/ec-preset-full 2.5.0` + `@ecl-twig/ec-components 2.5.3`. @ademarco what would be best/easier for you?

**Comment by emeryro** [comment]
just to say, it is indeed easier to have both things decoupled (that's why I highlighted it), but I also do think that it could be confusing for users
(I know, it is not really helping to take a decision...)

**Comment by ademarco** [comment]
For us it's best to just require one package, i.e. `@ecl-twig/ec-components`, and get all the components downloaded along-aside it, wheres such components live in separated repositories (meaning, they are downloaded as dependencies), or in a single one, it's the same for us.

Same goes for versioning, we are fine with anything, although having the same ECL version being used on `@ecl-twig/ec-components` would make it clearer for us.

**Comment by emeryro** [comment]
Here are the conclusions of the discussion:
- we use the same MAJOR.minor in both ECL CSS framework and twig templates (patches can be different)
- all the twig packages use the same version (not independent)

First version released will be 2.3.0

**Comment by ademarco** [comment]
That's perfect, thank you guys!
